---
title: "Hanadate, Shuhei (花立 修平)"
format: html
editor: visual
toc: TRUE
---

## Interest

Sample size planning (Sample size justification), Experimental design, Sequential analysis, Test theory, Item response theory, Bayesian modeling, Psychometrics, and R-lang.

Book hoarding, Martial Arts, Dharma and Soto Zen.

## ORCID

<https://orcid.org/0009-0003-7570-6446>

## Github

<https://github.com/hanadate>

## Certification

-   Certified ScrumMaster (2018/05\~2024/05)

-   Certified Scrum Product Owner (2018/04\~2024/04)

-   PMI Agile Certified Practitioner (2019/11\~2022/11)

-   SPSS Modeler Professional v3

-   IBM Certified Data Scientist

## License

-   Standard Motorcycle License (普通自動二輪車免許)

-   Class 1 Driver's License (普通自動車免許)

-   After-school Child Care Worker (放課後児童支援員)

-   Herbal Health Counselor (漢方養生指導士)

-   Boxer License (2021\~2023)

## Publication

1.  [**Hanadate, S**]{.underline}., & Yamaguchi, K. (2025, March 10). Simulation-based sensitivity analysis for sample size planning of Rasch family models. \[Preprint\] <https://doi.org/10.31219/osf.io/pu53j_v1>

## Poster

-   [**Hanadate, S.**]{.underline} & Yamaguchi, K. (2025 March). Simulation-based sensitivity analysis for sample size planning of Rasch family models. The Japan Statistical Society. Tokyo, Japan.

## Scientific Membership

-   Psychometric Society

-   Association for Psychological Science

-   Psychonomic Society

-   The Japan Association for Research on Testing (日本テスト学会)

-   The Behaviometric Society of Japan (日本行動計量学会)

-   The Japanese Psychological Association (日本心理学会)

-   The Japanese Statistical Society (日本統計学会)

## Award

-   General Manager Award of IBM Japan, 2019/2H.

## Biography

2024: Enroll in University of Tukuba for master's program in Psychology. SV: Yamaguchi, Kazuhiro.

2021: Be a father.

2016: Started to work as Consultant for data analytics and marketing \@IBM. The last position was a managing consultant who managed 2 or 3 projects parallelly and reporting line for a newbie team. Industries worked for: Pharma, Automotive, and Finance. Quitted it in 2024.

2012: Enrolled in Waseda University for undergraduate program in Psychology. Graduated in 2016. SV: Toyoda, Hideki.

2006: Enrolled in Waseda Junior & Senior High School. Graduated in 2012.

1993: Born in Kanagawa. Raised in Tokyo.

## Side Hustle

-   Boxing: In Waseda University, was a fly or bantam weight boxer for a club team, which produced a world champion and some japan champions. And 2021, it was 5 year blank after the graduation, proceeded into professional rings. Although the career was not successful, learned a lot.

-   Teaching Japanese: In my hometown Mitaka, working as a volunteer for Let's Learn Japanese (LLJ) in Mitaka International Society for Hospitality (MISHOP).

-   Supporting Research for high school students: In University of Tsukuba, working for Global Front-runner in Engeneering, Science & Technology (GFEST) to support research by high school students. Provided skills and knowledges about psychometrics to enhance their research.

    -   Relationships between Handwritings Style and Preferences.

    -   Gender differences for Trypophobia.

## Contact

hanadate.shuhei.tkb_gb\[atmark\]u.tsukuba.ac.jp

No social media account.
